version: '3.8'
services:
  app:
    build:
      context: .  # Builds from the current directory (includes Dockerfile)
      dockerfile: Dockerfile
    image: landing-page-demo  # Optional: Name for the built image
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - web
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/data', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  web:
    driver: bridge

